from .index import index
from .contact import *
from .about import about
from .login import *
from .profile import *
from .diet import diet
from .nutricionist import *
from .food import *
from .user import *