# Generated by Django 5.0 on 2024-01-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IW', '0003_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
